# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-02 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180802_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='message',
        ),
    ]
